package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cddesigntopics generated by hbm2java
 */
public class Cddesigntopics implements java.io.Serializable { 
	private static final long serialVersionUID = 1L;
	private Integer cddesignTopId;
	private Cdteachergroup cdteachergroup;
	private Teacher teacher;
	private String topics;
	private String topicsDescribtion;
	private Integer isSelfChoosed;
	private Set<Selfevaluation> selfevaluations = new HashSet<Selfevaluation>(0);
	private Set<Studentgroup> studentgroups = new HashSet<Studentgroup>(0);
	private Set<Cdchoosingrecord> cdchoosingrecords = new HashSet<Cdchoosingrecord>(0);
	private Set<Studentscore> studentscores = new HashSet<Studentscore>(0);

	public Cddesigntopics() {
	}

	public Cddesigntopics(Cdteachergroup cdteachergroup, Teacher teacher, String topics, String topicsDescribtion,
			Integer isSelfChoosed, Set<Selfevaluation> selfevaluations, Set<Studentgroup> studentgroups,
			Set<Cdchoosingrecord> cdchoosingrecords, Set<Studentscore> studentscores) {
		this.cdteachergroup = cdteachergroup;
		this.teacher = teacher;
		this.topics = topics;
		this.topicsDescribtion = topicsDescribtion;
		this.isSelfChoosed = isSelfChoosed;
		this.selfevaluations = selfevaluations;
		this.studentgroups = studentgroups;
		this.cdchoosingrecords = cdchoosingrecords;
		this.studentscores = studentscores;
	}

	public Integer getCddesignTopId() {
		return this.cddesignTopId;
	}

	public void setCddesignTopId(Integer cddesignTopId) {
		this.cddesignTopId = cddesignTopId;
	}

	public Cdteachergroup getCdteachergroup() {
		return this.cdteachergroup;
	}

	public void setCdteachergroup(Cdteachergroup cdteachergroup) {
		this.cdteachergroup = cdteachergroup;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getTopics() {
		return this.topics;
	}

	public void setTopics(String topics) {
		this.topics = topics;
	}

	public String getTopicsDescribtion() {
		return this.topicsDescribtion;
	}

	public void setTopicsDescribtion(String topicsDescribtion) {
		this.topicsDescribtion = topicsDescribtion;
	}

	public Integer getIsSelfChoosed() {
		return this.isSelfChoosed;
	}

	public void setIsSelfChoosed(Integer isSelfChoosed) {
		this.isSelfChoosed = isSelfChoosed;
	}

	public Set<Selfevaluation> getSelfevaluations() {
		return this.selfevaluations;
	}

	public void setSelfevaluations(Set<Selfevaluation> selfevaluations) {
		this.selfevaluations = selfevaluations;
	}

	public Set<Studentgroup> getStudentgroups() {
		return this.studentgroups;
	}

	public void setStudentgroups(Set<Studentgroup> studentgroups) {
		this.studentgroups = studentgroups;
	}

	public Set<Cdchoosingrecord> getCdchoosingrecords() {
		return this.cdchoosingrecords;
	}

	public void setCdchoosingrecords(Set<Cdchoosingrecord> cdchoosingrecords) {
		this.cdchoosingrecords = cdchoosingrecords;
	}

	public Set<Studentscore> getStudentscores() {
		return this.studentscores;
	}

	public void setStudentscores(Set<Studentscore> studentscores) {
		this.studentscores = studentscores;
	}

}
