package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cdteachergroup generated by hbm2java
 */
public class Cdteachergroup implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer cdteacherGroupId;
	private Cdplan cdplan;
	private Teacher teacher;
	private Set<Processassshedule> processassshedules = new HashSet<Processassshedule>(0);
	private Set<Teacher> teachers = new HashSet<Teacher>(0);
	private Set<Evalstandards> evalstandardses = new HashSet<Evalstandards>(0);
	private Set<Cddesigntopics> cddesigntopicses = new HashSet<Cddesigntopics>(0);

	public Cdteachergroup() {
	}

	public Cdteachergroup(Cdplan cdplan, Teacher teacher, Set<Processassshedule> processassshedules,
			Set<Teacher> teachers, Set<Evalstandards> evalstandardses, Set<Cddesigntopics> cddesigntopicses) {
		this.cdplan = cdplan;
		this.teacher = teacher;
		this.processassshedules = processassshedules;
		this.teachers = teachers;
		this.evalstandardses = evalstandardses;
		this.cddesigntopicses = cddesigntopicses;
	}

	public Integer getCdteacherGroupId() {
		return this.cdteacherGroupId;
	}

	public void setCdteacherGroupId(Integer cdteacherGroupId) {
		this.cdteacherGroupId = cdteacherGroupId;
	}

	public Cdplan getCdplan() {
		return this.cdplan;
	}

	public void setCdplan(Cdplan cdplan) {
		this.cdplan = cdplan;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Set<Processassshedule> getProcessassshedules() {
		return this.processassshedules;
	}

	public void setProcessassshedules(Set<Processassshedule> processassshedules) {
		this.processassshedules = processassshedules;
	}

	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

	public Set<Evalstandards> getEvalstandardses() {
		return this.evalstandardses;
	}

	public void setEvalstandardses(Set<Evalstandards> evalstandardses) {
		this.evalstandardses = evalstandardses;
	}

	public Set<Cddesigntopics> getCddesigntopicses() {
		return this.cddesigntopicses;
	}

	public void setCddesigntopicses(Set<Cddesigntopics> cddesigntopicses) {
		this.cddesigntopicses = cddesigntopicses;
	}

}
