package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer classId;
	private Major major;
	private String className;
	private Set<Student> students = new HashSet<Student>(0);

	public Classes() {
	}

	public Classes(Major major, String className, Set<Student> students) {
		this.major = major;
		this.className = className;
		this.students = students;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public Major getMajor() {
		return this.major;
	}

	public void setMajor(Major major) {
		this.major = major;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
