package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * College generated by hbm2java
 */
public class College implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer collegeId;
	private String collegeName;
	private Set<Major> majors = new HashSet<Major>(0);
	private Set<Teacher> teachers = new HashSet<Teacher>(0);

	public College() {
	}

	public College(String collegeName, Set<Major> majors, Set<Teacher> teachers) {
		this.collegeName = collegeName;
		this.majors = majors;
		this.teachers = teachers;
	}

	public Integer getCollegeId() {
		return this.collegeId;
	}

	public void setCollegeId(Integer collegeId) {
		this.collegeId = collegeId;
	}

	public String getCollegeName() {
		return this.collegeName;
	}

	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}

	public Set<Major> getMajors() {
		return this.majors;
	}

	public void setMajors(Set<Major> majors) {
		this.majors = majors;
	}

	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

}
