package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Major generated by hbm2java
 */
public class Major implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer majorId;
	private College college;
	private String majorName;
	private Set<Classes> classeses = new HashSet<Classes>(0);
	private Set<Cdplan> cdplans = new HashSet<Cdplan>(0);

	public Major() {
	}

	public Major(College college, String majorName, Set<Classes> classeses, Set<Cdplan> cdplans) {
		this.college = college;
		this.majorName = majorName;
		this.classeses = classeses;
		this.cdplans = cdplans;
	}

	public Integer getMajorId() {
		return this.majorId;
	}

	public void setMajorId(Integer majorId) {
		this.majorId = majorId;
	}

	public College getCollege() {
		return this.college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

	public String getMajorName() {
		return this.majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	public Set<Classes> getClasseses() {
		return this.classeses;
	}

	public void setClasseses(Set<Classes> classeses) {
		this.classeses = classeses;
	}

	public Set<Cdplan> getCdplans() {
		return this.cdplans;
	}

	public void setCdplans(Set<Cdplan> cdplans) {
		this.cdplans = cdplans;
	}

}
