package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Processassshedule generated by hbm2java
 */
public class Processassshedule implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer processAssShId;
	private Cdteachergroup cdteachergroup;
	private Teacher teacher;
	private Date startTime;
	private Date endTime;
	private String processName;
	private String processDescribtion;
	private Set<Processdocument> processdocuments = new HashSet<Processdocument>(0);

	public Processassshedule() {
	}

	public Processassshedule(Cdteachergroup cdteachergroup, Teacher teacher, Date startTime, Date endTime,
			String processName, String processDescribtion, Set<Processdocument> processdocuments) {
		this.cdteachergroup = cdteachergroup;
		this.teacher = teacher;
		this.startTime = startTime;
		this.endTime = endTime;
		this.processName = processName;
		this.processDescribtion = processDescribtion;
		this.processdocuments = processdocuments;
	}

	public Integer getProcessAssShId() {
		return this.processAssShId;
	}

	public void setProcessAssShId(Integer processAssShId) {
		this.processAssShId = processAssShId;
	}

	public Cdteachergroup getCdteachergroup() {
		return this.cdteachergroup;
	}

	public void setCdteachergroup(Cdteachergroup cdteachergroup) {
		this.cdteachergroup = cdteachergroup;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	public String getProcessDescribtion() {
		return this.processDescribtion;
	}

	public void setProcessDescribtion(String processDescribtion) {
		this.processDescribtion = processDescribtion;
	}

	public Set<Processdocument> getProcessdocuments() {
		return this.processdocuments;
	}

	public void setProcessdocuments(Set<Processdocument> processdocuments) {
		this.processdocuments = processdocuments;
	}

}
