package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Processdocument generated by hbm2java
 */
public class Processdocument implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer processDocId;
	private Processassshedule processassshedule;
	private Student student;
	private String documentName;
	private String documentUrl;
	private String tutorOpinion;
	private String upperDescribtion;
	private Date upperTime;
	private Integer isReaded;
	private Float score;

	public Processdocument() {
	}

	public Processdocument(Processassshedule processassshedule, Student student, String documentName,
			String documentUrl, String tutorOpinion, String upperDescribtion, Date upperTime, Integer isReaded,
			Float score) {
		this.processassshedule = processassshedule;
		this.student = student;
		this.documentName = documentName;
		this.documentUrl = documentUrl;
		this.tutorOpinion = tutorOpinion;
		this.upperDescribtion = upperDescribtion;
		this.upperTime = upperTime;
		this.isReaded = isReaded;
		this.score = score;
	}

	public Integer getProcessDocId() {
		return this.processDocId;
	}

	public void setProcessDocId(Integer processDocId) {
		this.processDocId = processDocId;
	}

	public Processassshedule getProcessassshedule() {
		return this.processassshedule;
	}

	public void setProcessassshedule(Processassshedule processassshedule) {
		this.processassshedule = processassshedule;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	public String getDocumentUrl() {
		return this.documentUrl;
	}

	public void setDocumentUrl(String documentUrl) {
		this.documentUrl = documentUrl;
	}

	public String getTutorOpinion() {
		return this.tutorOpinion;
	}

	public void setTutorOpinion(String tutorOpinion) {
		this.tutorOpinion = tutorOpinion;
	}

	public String getUpperDescribtion() {
		return this.upperDescribtion;
	}

	public void setUpperDescribtion(String upperDescribtion) {
		this.upperDescribtion = upperDescribtion;
	}

	public Date getUpperTime() {
		return this.upperTime;
	}

	public void setUpperTime(Date upperTime) {
		this.upperTime = upperTime;
	}

	public Integer getIsReaded() {
		return this.isReaded;
	}

	public void setIsReaded(Integer isReaded) {
		this.isReaded = isReaded;
	}

	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

}
