package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Replygroup generated by hbm2java
 */
public class Replygroup implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer replyGroupId;
	private String replyGroupName;
	private Set<Teacher> teachers = new HashSet<Teacher>(0);
	private Set<Replyplan> replyplans = new HashSet<Replyplan>(0);

	public Replygroup() {
	}

	public Replygroup(String replyGroupName, Set<Teacher> teachers, Set<Replyplan> replyplans) {
		this.replyGroupName = replyGroupName;
		this.teachers = teachers;
		this.replyplans = replyplans;
	}

	public Integer getReplyGroupId() {
		return this.replyGroupId;
	}

	public void setReplyGroupId(Integer replyGroupId) {
		this.replyGroupId = replyGroupId;
	}

	public String getReplyGroupName() {
		return this.replyGroupName;
	}

	public void setReplyGroupName(String replyGroupName) {
		this.replyGroupName = replyGroupName;
	}

	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

	public Set<Replyplan> getReplyplans() {
		return this.replyplans;
	}

	public void setReplyplans(Set<Replyplan> replyplans) {
		this.replyplans = replyplans;
	}

}
