package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Replyplan generated by hbm2java
 */
public class Replyplan implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer replyPlanId;
	private Replygroup replygroup;
	private Studentgroup studentgroup;
	private String replyName;
	private String replyDescribtion;
	private Date startTime;
	private Date endTime;
	private String replyLocation;
	private Set<Replyrecords> replyrecordses = new HashSet<Replyrecords>(0);

	public Replyplan() {
	}

	public Replyplan(Replygroup replygroup, Studentgroup studentgroup, String replyName, String replyDescribtion,
			Date startTime, Date endTime, String replyLocation, Set<Replyrecords> replyrecordses) {
		this.replygroup = replygroup;
		this.studentgroup = studentgroup;
		this.replyName = replyName;
		this.replyDescribtion = replyDescribtion;
		this.startTime = startTime;
		this.endTime = endTime;
		this.replyLocation = replyLocation;
		this.replyrecordses = replyrecordses;
	}

	public Integer getReplyPlanId() {
		return this.replyPlanId;
	}

	public void setReplyPlanId(Integer replyPlanId) {
		this.replyPlanId = replyPlanId;
	}

	public Replygroup getReplygroup() {
		return this.replygroup;
	}

	public void setReplygroup(Replygroup replygroup) {
		this.replygroup = replygroup;
	}

	public Studentgroup getStudentgroup() {
		return this.studentgroup;
	}

	public void setStudentgroup(Studentgroup studentgroup) {
		this.studentgroup = studentgroup;
	}

	public String getReplyName() {
		return this.replyName;
	}

	public void setReplyName(String replyName) {
		this.replyName = replyName;
	}

	public String getReplyDescribtion() {
		return this.replyDescribtion;
	}

	public void setReplyDescribtion(String replyDescribtion) {
		this.replyDescribtion = replyDescribtion;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getReplyLocation() {
		return this.replyLocation;
	}

	public void setReplyLocation(String replyLocation) {
		this.replyLocation = replyLocation;
	}

	public Set<Replyrecords> getReplyrecordses() {
		return this.replyrecordses;
	}

	public void setReplyrecordses(Set<Replyrecords> replyrecordses) {
		this.replyrecordses = replyrecordses;
	}

}
