package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Replyrecords generated by hbm2java
 */
public class Replyrecords implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer replyRecordId;
	private Replyplan replyplan;
	private Student student;
	private Teacher teacher;
	private String question;
	private String answers;
	private Date answerTime;

	public Replyrecords() {
	}

	public Replyrecords(Replyplan replyplan, Student student, Teacher teacher, String question, String answers,
			Date answerTime) {
		this.replyplan = replyplan;
		this.student = student;
		this.teacher = teacher;
		this.question = question;
		this.answers = answers;
		this.answerTime = answerTime;
	}

	public Integer getReplyRecordId() {
		return this.replyRecordId;
	}

	public void setReplyRecordId(Integer replyRecordId) {
		this.replyRecordId = replyRecordId;
	}

	public Replyplan getReplyplan() {
		return this.replyplan;
	}

	public void setReplyplan(Replyplan replyplan) {
		this.replyplan = replyplan;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswers() {
		return this.answers;
	}

	public void setAnswers(String answers) {
		this.answers = answers;
	}

	public Date getAnswerTime() {
		return this.answerTime;
	}

	public void setAnswerTime(Date answerTime) {
		this.answerTime = answerTime;
	}

}
