package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer stuId;
	private Account account;
	private Classes classes;
	private String studentId;
	private String stuName;
	private Set<Replyrecords> replyrecordses = new HashSet<Replyrecords>(0);
	private Set<Studentgroup> studentgroups = new HashSet<Studentgroup>(0);
	private Set<Processdocument> processdocuments = new HashSet<Processdocument>(0);
	private Set<Studentscore> studentscores = new HashSet<Studentscore>(0);
	private Set<Selfevaluation> selfevaluations = new HashSet<Selfevaluation>(0);
	private Set<Studentgroup> studentgroups_1 = new HashSet<Studentgroup>(0);

	public Student() {
	}

	public Student(Account account, Classes classes, String studentId, String stuName, Set<Replyrecords> replyrecordses,
			Set<Studentgroup> studentgroups, Set<Processdocument> processdocuments, Set<Studentscore> studentscores,
			Set<Selfevaluation> selfevaluations, Set<Studentgroup> studentgroups_1) {
		this.account = account;
		this.classes = classes;
		this.studentId = studentId;
		this.stuName = stuName;
		this.replyrecordses = replyrecordses;
		this.studentgroups = studentgroups;
		this.processdocuments = processdocuments;
		this.studentscores = studentscores;
		this.selfevaluations = selfevaluations;
		this.studentgroups_1 = studentgroups_1;
	}

	public Integer getStuId() {
		return this.stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	public Set<Replyrecords> getReplyrecordses() {
		return this.replyrecordses;
	}

	public void setReplyrecordses(Set<Replyrecords> replyrecordses) {
		this.replyrecordses = replyrecordses;
	}

	public Set<Studentgroup> getStudentgroups() {
		return this.studentgroups;
	}

	public void setStudentgroups(Set<Studentgroup> studentgroups) {
		this.studentgroups = studentgroups;
	}

	public Set<Processdocument> getProcessdocuments() {
		return this.processdocuments;
	}

	public void setProcessdocuments(Set<Processdocument> processdocuments) {
		this.processdocuments = processdocuments;
	}

	public Set<Studentscore> getStudentscores() {
		return this.studentscores;
	}

	public void setStudentscores(Set<Studentscore> studentscores) {
		this.studentscores = studentscores;
	}

	public Set<Selfevaluation> getSelfevaluations() {
		return this.selfevaluations;
	}

	public void setSelfevaluations(Set<Selfevaluation> selfevaluations) {
		this.selfevaluations = selfevaluations;
	}

	public Set<Studentgroup> getStudentgroups_1() {
		return this.studentgroups_1;
	}

	public void setStudentgroups_1(Set<Studentgroup> studentgroups_1) {
		this.studentgroups_1 = studentgroups_1;
	}

}
