package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

/**
 * Studentscore generated by hbm2java
 */
public class Studentscore implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Cddesigntopics cddesigntopics;
	private Student student;
	private Float replyScore;
	private Float attendanceScore;
	private Float examScore;
	private Float selEvScore;
	private Float totalScore;

	public Studentscore() {
	}

	public Studentscore(Cddesigntopics cddesigntopics, Student student, Float replyScore, Float attendanceScore,
			Float examScore, Float selEvScore, Float totalScore) {
		this.cddesigntopics = cddesigntopics;
		this.student = student;
		this.replyScore = replyScore;
		this.attendanceScore = attendanceScore;
		this.examScore = examScore;
		this.selEvScore = selEvScore;
		this.totalScore = totalScore;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cddesigntopics getCddesigntopics() {
		return this.cddesigntopics;
	}

	public void setCddesigntopics(Cddesigntopics cddesigntopics) {
		this.cddesigntopics = cddesigntopics;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Float getReplyScore() {
		return this.replyScore;
	}

	public void setReplyScore(Float replyScore) {
		this.replyScore = replyScore;
	}

	public Float getAttendanceScore() {
		return this.attendanceScore;
	}

	public void setAttendanceScore(Float attendanceScore) {
		this.attendanceScore = attendanceScore;
	}

	public Float getExamScore() {
		return this.examScore;
	}

	public void setExamScore(Float examScore) {
		this.examScore = examScore;
	}

	public Float getSelEvScore() {
		return this.selEvScore;
	}

	public void setSelEvScore(Float selEvScore) {
		this.selEvScore = selEvScore;
	}

	public Float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(Float totalScore) {
		this.totalScore = totalScore;
	}

}
