package com.cds.entity;
// Generated 2016-4-20 18:11:49 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Term generated by hbm2java
 */
public class Term implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer termId;
	private String termName;
	private Set<Cdplan> cdplans = new HashSet<Cdplan>(0);

	public Term() {
	}

	public Term(String termName, Set<Cdplan> cdplans) {
		this.termName = termName;
		this.cdplans = cdplans;
	}

	public Integer getTermId() {
		return this.termId;
	}

	public void setTermId(Integer termId) {
		this.termId = termId;
	}

	public String getTermName() {
		return this.termName;
	}

	public void setTermName(String termName) {
		this.termName = termName;
	}

	public Set<Cdplan> getCdplans() {
		return this.cdplans;
	}

	public void setCdplans(Set<Cdplan> cdplans) {
		this.cdplans = cdplans;
	}

}
